### ISSUE TITLE
parseSKU() returns NaN effect when untradable flag is used

### ISSUE THREAD

**Issue by piman51277** [automatedtf/catalog#5]
When the `untradable` flag is used, the `effect` parameter is returned as `NaN`

Input: 
`30187;5;u14;uncraftable;untradable`
Expected Output:
`
{
  defindex: 30187,
  quality: 5,
  craftable: false,
  effect: 14,
  tradable: false
}
`
Actual Output
`
{
  defindex: 30187,
  quality: 5,
  craftable: false,
  effect: NaN,
  tradable: false
}
`

Testing Code:
```
import {parseSKU} from '@automatedtf/catalog';
console.log(parseSKU("30187;5;u14;uncraftable;untradable"));
```

**Comment by piman51277** [comment]
This seems to be an issue with tf2-item-format. It is possible to work around the issue, but I would advise updating to a newer version instead.

**Comment by HilliamT** [comment]
This has been fixed in https://github.com/automatedtf/catalog/commit/589070915613e3ea9ac83bc6e71ee41c941f00a8

Tests have been added [here](https://github.com/automatedtf/catalog/commit/589070915613e3ea9ac83bc6e71ee41c941f00a8#diff-ffd7190a8ea36fb127d3df924dee94fc905b4e7aef5a0f45d2f00e7cd934cb98) to ensure that this has been fixed.
